---
- name: Destroy VM
  hosts: kvm
  gather_facts: no
  tasks:
    - name: Stop VM
      virt: name={{vm_hostname}} state=destroyed
    - name: Undefine VM
      virt: name={{vm_hostname}} command=undefine
    - name: Remove disk
      lvol: vg={{kvm_vg}} lv={{vm_hostname}}.qcow2 state=absent force=yes
  vars_prompt:
    - name: "vm_hostname"
      prompt: "Enter VM hostname"
      private: no

