- name: Generate Kubernetes PKI
  hosts: 127.0.0.1
  gather_facts: no
  tasks:
    - name: Create PKI dir
      file:
        path: private/kubernetes
        state: directory
    - name: Generate CA key
      openssl_privatekey:
        path: private/kubernetes/ca.key
    - name: Generate CA CSR
      openssl_csr:
        path: private/kubernetes/ca.csr
        privatekey_path: private/kubernetes/ca.key
        common_name: kubernetes
        basicConstraints:
          - 'CA:TRUE'
    - name: Sign CA CSR
      openssl_certificate:
        path: private/kubernetes/ca.crt
        privatekey_path: private/kubernetes/ca.key
        csr_path: private/kubernetes/ca.csr
        provider: selfsigned
    - name: Generate admin key
      openssl_privatekey:
        path: private/kubernetes/admin.key
    - name: Generate admin CSR
      openssl_csr:
        path: private/kubernetes/admin.csr
        privatekey_path: private/kubernetes/admin.key
        common_name: admin
        organization_name: 'system:masters'
    - name: Sign admin CSR
      openssl_certificate:
        path: private/kubernetes/admin.crt
        privatekey_path: private/kubernetes/admin.key
        csr_path: private/kubernetes/admin.csr
        provider: selfsigned

- name: Generate Kubernetes node certificates
  hosts: kubernetes2
  tasks:
    - include_tasks: generate-nodecerts.yml
