---
- name: Test1
  hosts: vyos
  connection: local
  tasks:
    - name: Backup config
      vyos_config:
        backup: yes
        provider: "{{ cli }}"
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: cross
      ssh_keyfile: "/root/.ssh/id_rsa"
      timeout: 20
