- name: Check OS
  assert:
    that:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"
    msg: "Unsupported OS: {{ansible_distribution}} {{ansible_distribution_major_version}}"

- name: Disable selinux
  selinux:
    state: disabled

- name: Turn swap off
  command: swapoff -a

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

- name: Install base packages
  yum: name={{ item }}
    state=present
    disable_gpg_check=yes
  with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl

- name: Install kubelet sysconfig
  template: src=kubelet.config dest=/etc/sysconfig/kubelet
  notify:
    - restart kubelet

- name: Install docker sysconfig
  template: src=docker.config dest=/etc/sysconfig/docker
  notify:
    - reload docker

- name: Open kubernetes ports
  firewalld: port={{item}} permanent=true state=enabled immediate=yes
  with_items:
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250/tcp"
    - "10251/tcp"
    - "10252/tcp"
    - "10255/tcp"
    - "30000-32767/tcp"
    - "8472/udp"

- name: Enable/start kubernetes services
  service: name={{item}} state=started enabled=yes
  with_items:
    - docker
    - kubelet

