- name: Check OS
  assert:
    that:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"
    msg: "Unsupported OS: {{ansible_distribution}} {{ansible_distribution_major_version}}"

- name: Install Ceph repo
  template: src=ceph.repo.j2 dest=/etc/yum.repos.d/ceph.repo

- name: Install Ceph packages
  yum: name={{ item }}
    state=present
  with_items:
    - ceph
    - python-firewall

- name: Open Ceph ports
  firewalld: port={{item}} permanent=true state=enabled immediate=yes
  with_items:
    - "6789/tcp"
    - "6800-7300/tcp"
