- name: Check OS
  assert:
    that:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"
    msg: "Unsupported OS: {{ansible_distribution}} {{ansible_distribution_major_version}}"

- name: Check variables
  assert:
    that:
    - "ceph_fsid is defined"
    msg: "Critical variable undefined"

- name: Install Ceph repo
  template: src=ceph.repo.j2 dest=/etc/yum.repos.d/ceph.repo


- name: Install Ceph packages
  yum: name={{ item }}
    state=present
  with_items:
    - ceph
    - python-firewall

- name: Open Ceph ports
  firewalld: port={{item}} permanent=true state=enabled immediate=yes
  with_items:
    - "6789/tcp"
    - "6800-7300/tcp"

- name: Install ceph.conf
  template: src=ceph.conf.j2 dest=/etc/ceph/ceph.conf
  notify: restart ceph

- name: Generate ceph admin key
  command: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *' creates=/etc/ceph/ceph.client.admin.keyring
  register: generated_key
  when: ansible_nodename == ceph_bootstrap_node

- name: Retrieve ceph admin key
  fetch: src=/etc/ceph/ceph.client.admin.keyring dest=private/ceph/ceph.client.admin.keyring flat=yes
  when: ansible_nodename == ceph_bootstrap_node

- name: Ensure ceph admin key exists
  copy: src=private/ceph/ceph.client.admin.keyring dest=/etc/ceph/ceph.client.admin.keyring owner=0 group=0 mode=0600

- name: Generate bootstrap-osd keyring
  command: ceph-authtool --create-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --gen-key -n client.bootstrap-osd --cap mon 'profile bootstrap-osd' creates=/var/lib/ceph/bootstrap-osd/ceph.keyring
  when: ansible_nodename == ceph_bootstrap_node

- name: Retrieve bootstrap-osd keyring
  fetch: src=/var/lib/ceph/bootstrap-osd/ceph.keyring dest=private/ceph/bootstrap-osd.keyring flat=yes
  when: ansible_nodename == ceph_bootstrap_node

- name: Ensure bootstrap-osd keyring exists
  copy: src=private/ceph/bootstrap-osd.keyring dest=/var/lib/ceph/bootstrap-osd/ceph.keyring owner=0 group=0 mode=0600

- name: Create mon directory
  file: path=/var/lib/ceph/mon/ceph-{{ansible_hostname}}/ owner=ceph group=ceph state=directory

- name: Check if mon is bootstrapped
  stat: path=/var/lib/ceph/mon/ceph-{{ansible_hostname}}/done
  register: monitor_check

- import_tasks: mon-bootstrap.yml
  when: ansible_nodename == ceph_bootstrap_node and not monitor_check.stat.exists

#monitor assumed to be started and responding by this point

- import_tasks: mon-add.yml
  when: ansible_nodename != ceph_bootstrap_node and not monitor_check.stat.exists

- name: Ensure safe permissions of monitor dir
  file: path=/var/lib/ceph/mon/ceph-{{ansible_hostname}}/ owner=ceph group=ceph recurse=yes

- name: Enable/start monitor
  service: name=ceph-mon@{{ansible_hostname}} state=started enabled=yes

# cluster should be fully set up according to provided hosts

- name: Create mgr directory
  file: path=/var/lib/ceph/mgr/ceph-{{ansible_hostname}}/ owner=ceph group=ceph state=directory

- name: Retrieve manager key
  command: ceph auth get-or-create mgr.{{ansible_hostname}} mon 'allow profile mgr' osd 'allow *' mds 'allow *'
  register: mgr_key

- name: Install manager key
  copy: dest=/var/lib/ceph/mgr/ceph-{{ansible_hostname}}/keyring owner=ceph group=ceph mode=0600 content="{{mgr_key.stdout}}\n"

- name: Enable/start manager
  service: name=ceph-mgr@{{ansible_hostname}} state=started enabled=yes

- name: Enable dashboard
  command: ceph mgr module enable dashboard
