- name: Check OS
  assert:
    that:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"
    msg: "Unsupported OS: {{ansible_distribution}} {{ansible_distribution_major_version}}"

- name: Install sshd_config
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0600
    validate='/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd

- name: Install chrony.conf
  template: src=chrony.conf.j2
    dest=/etc/chrony.conf
    backup=yes
    owner=0 group=0 mode=0644
  notify:
  - restart chronyd

- name: Install InfluxDB repo
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d/influxdb.repo

- name: Install base packages
  yum: name={{["nano","mtr","rsync","screen","wget","telegraf","deltarpm","iptables-services"] }}
    state=present

- name: Disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: Install iptables config
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify:
  - restart iptables

- name: Start iptables
  service: name=iptables state=started enabled=yes

- name: Disable NetworkManager
  service: name=NetworkManager state=stopped enabled=no
  notify:
    - restart network

- name: Setup root forwarder
  copy: content={{ admin_email }} dest=/root/.forward owner=0 group=0 mode=0600

- name: Install telegraf config
  template: src=telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf
  notify:
    - reload telegraf

- name: Install telegraf sudo rules
  copy:
    src: telegraf.sudo
    dest: /etc/sudoers.d/telegraf
  when: ansible_virtualization_role == 'host'

- name: Start and enable telegraf
  service: name=telegraf state=started enabled=yes
