- name: Install sshd_config
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd

- name: Install base packages
  package: name={{ item }}
    state=present
  with_items:
    - nano
    - epel-release
    - mtr

#- name: Install InfluxDB repo
#  copy:
#    src: influxdb.repo
#    dest: /etc/yum.repos.d/influxdb.repo
